### ISSUE TITLE
eth balance incorrect...(staking UI)

### ISSUE THREAD

**Issue by orionNode** [nucypher/nuit#105]
the eth balance of my worker is incorrect in Staking UI
Also a better description of what estimated runway is would be nice

**Comment by KPrasch** [comment]
Hey @orionNode Thanks for opening this issue!

> the eth balance of my worker is incorrect in Staking UI

Can you elaborate a bit? 😄 

> Also a better description of what estimated runway is would be nice

Excellent suggestion!  We can include something in the tooltip.

**Comment by orionNode** [comment]
Oh yea... on the worker eth balance it just said 0.00
There's less than 20.00 in currently..will send more over, but the display wasn't matching the balance

**Comment by orionNode** [comment]
Not a major issue btw. Should've looked to see if there was a priority selection when I opened this. Hardly a minor one for me. Just something I noticed.

**Comment by KPrasch** [comment]
All feedback is welcomed :-)  We'll handle triage and prioritization on our side.

I think there is a rounding error and the precision is too low.  We'll take a look!
