### ISSUE TITLE
Extending the stake

### ISSUE THREAD

**Issue by IErk** [nucypher/nuit#107]
Hi, nice NU UI, thank you. 

First issue for me: 
1. Extending the substake
![Capture 1](https://user-images.githubusercontent.com/83816493/117438579-a44d9580-af29-11eb-90a6-793af2fc3418.PNG)
2. When trying to extend and slide the scale it moves to the max and becomes unresponsive.
![Capture 2](https://user-images.githubusercontent.com/83816493/117438930-1f16b080-af2a-11eb-8ea7-0a9c437f52a0.PNG)

Kind regards

**Comment by KPrasch** [comment]
Thanks for opening this issue @IErk !  We'll have a look at it.  Which browser were you using when this happened?

**Comment by IErk** [comment]
Hi, thank you for reverting. I am using Chrome. Let me try Edge, though need to sort Metamask extensions …

 

Kind regards, Igor

**Comment by IErk** [comment]
But the slider to adjust lock-in period works fine with Add Sub-stake function.

 

Igor

**Comment by IErk** [comment]
FYI, Have tried with Microsoft Edge and is the same.

 

Kind regards.

**Comment by IErk** [comment]
Great, works well. Thank you.

**Comment by vepkenez** [comment]
> Great, works well. Thank you.

Thanks so much for testing! 🏆
