### ISSUE TITLE
Display (total) stake duration

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nuit#115]
"Period Committed To" From the specification:
![Screenshot from 2021-05-08 13-47-58](https://user-images.githubusercontent.com/679404/117553053-0ed30400-b004-11eb-98fb-632410544925.png)

**Comment by vepkenez** [comment]
Where is this supposed to be?  What is the context?

**Comment by KPrasch** [comment]
I can imagine it fitting well in a few places, but the spec has is on Manage > Running > Staker.
