### ISSUE TITLE
Side-by-side layout of restaking and winddown controls

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nuit#116]
From the spec:

![Screenshot from 2021-05-08 13-48-15](https://user-images.githubusercontent.com/679404/117553062-17c3d580-b004-11eb-979a-fd632473038c.png)

**Comment by vepkenez** [comment]
I ditched this because it was inconsistent with the other similar box, complicated and less flexible to implement and in reality I suspect was not so thoughtfully ripped from stakeit-space anyway so we should not feel like we need to slavishly follow it.

**Comment by KPrasch** [comment]
In my opinion the overall page geometry is a bit more interesting and more efficient with them side-by-side, especially considering they don't need any content other than "off" or "on".  This issue is not of great importance - if you'd prefer to close it, I won't be disappointed.

**Comment by vepkenez** [comment]
Actually I agree.  And now that we have some time let’s make it right.

**Comment by KPrasch** [comment]
This issue is no longer relevant with the transition to the Threshold network.
