### ISSUE TITLE
Show locked periods and unlocking date when creating a new stake

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nuit#127]
Currently only *days* are shown however, it will be more informative for some users to see the duration depicted in periods and even the end date (if wind down is enabled).

**Comment by vepkenez** [comment]
@KPrasch not sure if you know this but all dates using the `<Period>` component can be clicked/tapped to toggle between date and period display.

**Comment by KPrasch** [comment]
> @KPrasch not sure if you know this but all dates using the `<Period>` component can be clicked/tapped to toggle between date and period display.

Yes - I've noticed.  Excellent feature IMO 😄 

That makes it even easier to address this issue, since we'll be able to have both the period duration and the date in one go.  I wasn't quite sure if it also worked for *duration*.

**Comment by vepkenez** [comment]
Maybe we need to make that more obvious?  They are blue... maybe an underline also?

**Comment by KPrasch** [comment]
> Maybe we need to make that more obvious? They are blue... maybe an underline also?

Perhaps just some hover effects.  I like the subtlety.

**Comment by vepkenez** [comment]
> also worked for _duration_.

Yeah it doesn't right now.  I guess I could make a `<Periods>` component that works for linear durations.
