### ISSUE TITLE
Cannot create stake for <= 14 days

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nuit#128]
EDIT: The minimum stake duration is 4 periods, so we need to raise the floor of the slider.

I am unable to create a new stake or sub-stake for less than "21 days".  MetaMask reports expected transaction error before signing, and it does indeed fail if I proceed past the warning.

![Screenshot from 2021-05-11 11-08-02](https://user-images.githubusercontent.com/679404/117864193-631af580-b249-11eb-9ff0-675f5e566d3b.png)

**Comment by derekpierre** [comment]
You shouldn't be able to. Min stake length is 4 periods (28 days).
