### ISSUE TITLE
Helvetica Neue alternates?

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nuit#20]
The Figma spec calls for Helvetica Neue, but many OSS operating systems do not ship it.  Shall we license and host it as a TTF (too expensive IMO) or just use another font? What is a good font alternative?  I've tried out "NimbusSans" and at least to my eye looks *very* close to the real thing.  @fjarri suggests "OpenSans".

**Comment by fjarri** [comment]
If you want a closer alternative, there's also Liberation Sans. But I personally like the look of Open Sans more.

A [comparison tool](http://www.identifont.com/differences?first=Open+Sans&second=Helvetica+Neue&q=Go) if you want to see the differences:

![Screen Shot 2021-04-24 at 13 50 55](https://user-images.githubusercontent.com/30720/115972594-2e4a3700-a504-11eb-9400-7c5cbb53544e.jpg)

**Comment by derekpierre** [comment]
We use Basis Grotesque on our website - pretty sure we already paid for it.

![Screen Shot 2021-04-26 at 9 45 26 AM](https://user-images.githubusercontent.com/19150641/116092975-4640c880-a674-11eb-9a6e-92a3d650e239.png)

**Comment by fjarri** [comment]
Seeing as how our software is under GPL, my vote would go for a font with an open source license (for the site too, perhaps).

**Comment by KPrasch** [comment]
Using Open Sans for now.

**Comment by cygnusv** [comment]
At the very least, the network name should use "Basis Grotesque". Current font looks very different from our brand.
Also, font divergence in an app like this would be one of the first things that would trigger my spidersense.

**Comment by KPrasch** [comment]
Addressed enough for closure in #78.  Switched to using *basis-grotesque-medium*, *gt-america-mono-regular*, and *Open Sans* for longer test blobs.
