### ISSUE TITLE
Improvements to landing page chart

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nuit#26]
![image](https://user-images.githubusercontent.com/2564234/116271871-b0df2a80-a780-11eb-80fa-b5ababcfc755.png)

- [ ] Round to 2 decimals (maybe even no decimals here)
- [ ] Use thousands separators
- [ ] Harmonize genesis and current eras by averaging historic data by weeks. Otherwise, the chart will look weird.

**Comment by KPrasch** [comment]
Thanks for the feedback @cygnusv !

**Comment by KPrasch** [comment]
Closed by #45
