### ISSUE TITLE
Sitewide Informational Copy

### ISSUE THREAD

**Issue by vepkenez** [nucypher/nuit#27]
There are dozens of instances of explanatory text that have `lorem ipsum`
I could really use help populating this.
Maybe I will sparkle some TODOs where it is found to make it easy and we can go through it on a call.

**Comment by derekpierre** [comment]
@vepkenez / @KPrasch now that we've had some linked PR merges, can this issue be closed for the "Public Beta", or are there other outstanding areas? Additional improvements to copy can be done post Public-Beta.

**Comment by derekpierre** [comment]
Closing as addressed by linked PRs - additional copy can be added in follow-up issues.
