### ISSUE TITLE
Remaining (Essential) Contract Write Functionality

### ISSUE THREAD

**Issue by vepkenez** [nucypher/nuit#29]
- [x] Migrate Stake
- [x] Bond Worker 
- [x] Create Stake
- [x] Prolong Stake
- [x] Divide Stake
- [x] Withdraw NU rewards

Moved out of Public Beta Milestone via #38 
~~- [ ] Add To Stake~~
~~- [ ] Mint (only for the end of the stake)~~
~~- [ ] Merge Stakes~~
~~- [ ] Remove Inactive~~
~~- [ ] Withdraw Policy Rewards~~

**Comment by derekpierre** [comment]
Are these already provided (nice to haves)?
- [ ] Mint (only for the end of the stake)
- [x] Merge Stakes
- [x] Remove Inactive

**Comment by vepkenez** [comment]
> Are these already provided (nice to haves)?
> 
> * [ ]  Mint (only for the end of the stake)
> * [ ]  Merge Stakes
> * [ ]  Remove Inactive

added these

**Comment by derekpierre** [comment]
Created #38 so that specific functionality can be focused on for Public Beta. The others can be added afterward.

**Comment by derekpierre** [comment]
Should we just bump "Withdraw Policy Rewards" out of Public-Beta? Doesn't feel like it is needed for beta; we can move it to #38 .

**Comment by KPrasch** [comment]
Agreed!
