### ISSUE TITLE
Show dates related to stake start and end instead of just period numbers

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nuit#32]
<img width="323" alt="Screen Shot 2021-04-27 at 12 00 07 PM" src="https://user-images.githubusercontent.com/19150641/116274770-f552d200-a750-11eb-817a-fa49b98578da.png">

Showing "start" and "end" values with only period numbers isn't intuitive. Perhaps add the actual date and then have the period number of parentheses, or ... ?

**Comment by vepkenez** [comment]
closed in #51
