### ISSUE TITLE
Bond Worker button on in New Stake Flow throws TypeError

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nuit#50]
Clicking the bond worker button throws an error

![Screenshot from 2021-05-03 08-50-08](https://user-images.githubusercontent.com/679404/116899610-a0013f80-abec-11eb-8480-af5e1de666de.png)

![Screenshot from 2021-05-03 08-40-21](https://user-images.githubusercontent.com/679404/116899468-6e887400-abec-11eb-829b-0db94b28d13e.png)

**Comment by vepkenez** [comment]
closed in #51
