### ISSUE TITLE
Cannot create new stake longer than 100 days

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nuit#53]
![Screenshot from 2021-05-03 11-36-10](https://user-images.githubusercontent.com/679404/116917700-db5b3880-ac03-11eb-97cf-25071a338743.png)

**Comment by vepkenez** [comment]
What is the actual limit for stake duration?  2 years?  Some number of periods?

**Comment by cygnusv** [comment]
There's no limit in the contract, but perhaps we should introduce it in the UI to avoid mistakes. Average users won't need to lock for more than, say, 2 years, as max rewards are at 1 year anyway. If someone wants to create a longer stake, let them use the CLI (which gives you a warning, IIRC)

**Comment by vepkenez** [comment]
I put a (soft) limit of 3 years and also made it so the ROI % tops out at one year.

I also made it so any value can be typed in by power users.
