### ISSUE TITLE
Implement Mobile Layout

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nuit#64]

**Comment by vepkenez** [comment]
in progress https://github.com/nucypher/nuit/pull/71
Feel free to continue.

**Comment by derekpierre** [comment]
Closed via #72 ?

**Comment by KPrasch** [comment]
Good progress thus far but still a handful of unresolved low resolution issues to address.  Let's leave this one open until more of the spec'd mobile layout is implemented.

**Comment by vepkenez** [comment]
Recent changes caused the header to look like this on mobile.
<img width="370" alt="Screen Shot 2021-05-05 at 05 20 54" src="https://user-images.githubusercontent.com/188812/117140048-c694b700-ad61-11eb-92ae-bfbcdcb831e1.png">

A lot of nice improvements but if it breaks functionality it's not better :)

**Comment by KPrasch** [comment]
@vepkenez - Addressed your above comment in #98

**Comment by vepkenez** [comment]
In my opinion we should close this and improve the mobile experience specific  issue by issue.

This issue is way too broad and it is in fact addressed.  We do have a fully functional mobile site working now.

it has some bugs.  Let’s make issues for those.

**Comment by KPrasch** [comment]
I agree, let's continue forward with better scoped issues. #98 has closed out a number of the outstanding mobile layout issues.
