### ISSUE TITLE
withdraw amount should be 0

### ISSUE THREAD

**Issue by LeapM** [nucypher/nuit#65]
The withdraw amount should be 0, 

2,683.096 NU was locked

![image](https://user-images.githubusercontent.com/12907236/116960744-e67d9980-acd3-11eb-94e1-56300637eb3c.png)
![image](https://user-images.githubusercontent.com/12907236/116960755-ed0c1100-acd3-11eb-9c3c-2083eacf7bae.png)

**Comment by vepkenez** [comment]
Thanks for reporting.  Is this for a stake that was newly created and starts next period by any chance?
