### ISSUE TITLE
Issue with Safari integration

### ISSUE THREAD

**Issue by SurlyKiwi** [nucypher/nuit#66]
If you paste something in the worker address window your screen goes white. So far I've only noticed this on safari, chrome works.
<img width="1337" alt="Screen Shot 2021-05-04 at 12 40 31 AM" src="https://user-images.githubusercontent.com/83137250/116961463-63c3f280-ac71-11eb-8da5-075ea20161ac.png">
 fine.

**Comment by vepkenez** [comment]
same as #69
