### ISSUE TITLE
White screen when clicking New Stake with Metamask connected

### ISSUE THREAD

**Issue by SurlyKiwi** [nucypher/nuit#69]

**Comment by KPrasch** [comment]
Thanks for the report.

Interesting, Looks like a staging server issue.  Errors appear on page load.
![Screenshot from 2021-05-03 23-35-08](https://user-images.githubusercontent.com/679404/116968168-d086bf00-ac68-11eb-994f-052211f8ed22.png)

@vepkenez - Send help! I've tried identifying a Syntax Error, but it does not happen locally 😐

**Comment by vepkenez** [comment]
Issue was caused by building in OSX yarn instead of docker yarn.
