### ISSUE TITLE
New stake creation allows dangerously long duration

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nuit#88]
Anything > 365 days warrants interception or preventing the user from inadvertently locking for longer than intended.  Currently the slider supports 1000+ locked days.

![Screenshot from 2021-05-05 11-44-48](https://user-images.githubusercontent.com/679404/117193186-6b7db700-ad97-11eb-9409-bad1cd34ecb0.png)

**Comment by vepkenez** [comment]
Fixed in #92
