### ISSUE TITLE
Toggle winddown text

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nuit#93]
![image](https://user-images.githubusercontent.com/2564234/117209569-cb577a80-adf6-11eb-97a0-9b1c0914fe4d.png)

* Unify "wind down" vs "winddown". I'd stick to "wind down".
* Hyperlink style not shown ("See Winding down for more information" has same color than the other text
* The text needs more flow. You can notice is borrowed from a longer text (in this case, our docs). I'd lean towards removing first sentence, and showing two bullets (one for ON and one for OFF), and an additional line with "see more info".

**Comment by KPrasch** [comment]
Improved in #98 

![Screenshot from 2021-05-06 04-04-20](https://user-images.githubusercontent.com/679404/117288279-2e113c00-ae20-11eb-90f8-d49e62bc3a60.png)

**Comment by KPrasch** [comment]
Closed by #98 - Let's open a follow-up issue for additional changes on this component.
