### ISSUE TITLE
Harmonize terminology

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nuit#99]
**Substakes vs Sub-stakes:**
![image](https://user-images.githubusercontent.com/2564234/117280870-5706f080-ae63-11eb-8352-ad0e2b4c89a0.png)

**NU  vs  Nu:**
![image](https://user-images.githubusercontent.com/2564234/117283722-57ed5180-ae66-11eb-993a-36a5d3171b9c.png)

**Comment by KPrasch** [comment]
Closed by #98
